Bookers2/config/routes.rb
Rails.application.routes.draw do
   root to: "homes#top"
   get 'home/about' => "homes#about"

   devise_for :users

   resources :users, only: [:show, :index, :update, :edit]
   resources :books, only: [:show, :index, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
   end

   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

Bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers2/app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

Bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  belongs_to :book
end

Bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

Bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :uniqueness => true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image
end

Bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログイン前
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

Bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.build(book_comment_params)
    comment.book_id = @book.id
    comment.save
    render 'book_comments/index'
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    render 'book_comments/index'
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

Bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # book詳細画面の新期投稿フォームにはBook.new,詳細にはBook.find(parama[:id])を入れたい
  # Book.new =>@book_newで統一。

  def show
    @book_new = Book.new

    @book = Book.find(params[:id])
    @user = @book.user

    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @book_new = Book.new
    @books = Book.all
  end
  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book_new)
    else
      @user = current_user
      @books = Book.all
      # render先はいつもbooks#indexにいく。
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    else
      render"edit"
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
   @book = Book.find(params[:id])
   @book.destroy
   redirect_to books_path
  end


  private
   def book_params
     params.require(:book).permit(:title, :body)
   end


end

Bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.build(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end

end

Bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

Bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Book.new =>@book_newで統一。

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
       redirect_to user_path(current_user)
    else
       render :edit
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

Bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Bookers2/app/helpers/books_helper.rb
module BooksHelper
end

Bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers2/app/helpers/users_helper.rb
module UsersHelper
end

Bookers2/app/views/book_comments/_form.html.erb
<div class="row">
  <!--@bookで/books/:book_id/book_commentsの:book_idを取得するのさ〜〜！！-->
  <%= form_with model: [book, book_comment], url: book_book_comments_path(@book), remote:true do |f| %>
  <div class="comment_form">
    <%= f.text_area :comment, class:"form-control", size:"90x3" %>
    <%= f.submit "送信" %>
  </div>
  <% end %>
</div>

Bookers2/app/views/book_comments/_index.html.erb
<table class="table table-hover table-inverse">
  <tbody>
    <% book.book_comments.each do |comment| %>
    <tr>
      <td>
        <%= link_to user_path(comment.user.id) do %>
          <%= attachment_image_tag comment.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %><br />
          <%= comment.user.name %>
        <% end %>
      </td>
      <td><%= comment.comment %></td>
        <!--コメント投稿ユーザなら表示↓-->
      <% if comment.user == current_user %>
      <td><%= link_to "Destroy", book_book_comment_path(comment.book_id, comment.id), class:'btn btn-danger', method: :delete, remote: true %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

Bookers2/app/views/book_comments/index.js.erb
<!--！！html("ーー")の"つけ忘れ注意-->
$("#comment_list").html("<%= j(render 'book_comments/index', book: @book) %>");
$("textarea").val('');

Bookers2/app/views/books/_errors.html.erb
<!--エラーメッセージ-->
<% if model.errors.any? %>
  <div id="error-box">
    <h3>
      <%= pluralize(model.errors.count, "error") %> prohibited this book from being saved:
    </h3>
    <div id="error-messages">
      <ul>
        <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

Bookers2/app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <font color="red">♥<%= book.favorites.count %></font>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
     ♥<%= book.favorites.count %>
  <% end %>
<% end %>

Bookers2/app/views/books/_user.html.erb
<!--ユーザー情報-->
<h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg", class:'mb-3' %>
  <table class="table table-hover table-inverse">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
<div class="row">
  <!--% if user.id == current_user.id % -->
    <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  <!--% end %-->
</div>

<!--新期投稿-->
<h2 class="mt-3">New book</h2>
  <%= form_with model: book, url: "/books", local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book",class: 'btn btn-success' %>
  </div>
  <% end %>

Bookers2/app/views/books/edit.html.erb
<div class="col-md-6 mx-auto">
  <h2>Editing Book</h2>
  <%= form_with model: @book, local:true do |f| %>
<!--erroe messages-->
  <%= render 'books/errors', model: f.object %>
<!---->
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, "opinion" %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Book", class: 'btn btn-success' %>
  </div>
  <% end %>
  <div class="row">
    <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
  </div>
</div>

Bookers2/app/views/books/index.html.erb
<!--Books index-->
<div class="container px-5 px-sm-0">
<!--erroe messages-->
<%= render 'books/errors', model: @book_new %>
  <div class="row">
  <!--User info, New book-->
    <div class="col-md-3">
      <%= render partial: 'books/user', locals: {user: @user, book: @book_new} %>
    </div>

  <!--Books一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <!--あとで各linkの追加-->
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td>
              <!--いいねボタンを非同期通信で行う-->
              <div id="favorite_<%= book.id %>">
                <%= render partial: 'favorites/favorite', locals: {book: book} %>
              </div>
              <!--ここまで-->
            </td>
            <td>
              コメント数：<%= book.book_comments.count %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

Bookers2/app/views/books/show.html.erb
<!--Books show. ※Book.new => @booka-->
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--User info, New book-->
    <div class="col-md-3">
      <%= render partial: 'books/user', locals: {user: @user, book: @book_new} %>
    </div>

    <!--Book詳細-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= attachment_image_tag @book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %><br />
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td>
              <!--いいねボタンを非同期通信で行う-->
              <div id="favorite_<%= @book.id %>">
                <%= render partial: 'favorites/favorite', locals: {book: @book} %>
              </div>
              <!--ここまで-->
            </td>
            <td>
              コメント数：<%= @book.book_comments.count %>
            </td>
            <!--作成ユーザなら表示↓-->
            <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@book.id), class:'btn btn-danger', method: :delete, data: {confirm: "「#{@book.title}」を削除します。"} %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <!--更新したい画面（コメント一覧）-->
      <div id="comment_list">
        <%= render partial: 'book_comments/index', locals: { book: @book } %>
      </div>
      <!--↑↑-->
      <div id="comment_form">
        <%= render partial: 'book_comments/form', locals: { book_comment: @book_comment, book: @book } %>
      </div>
    </div>
  </div>
</div>

Bookers2/app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book),method: :delete, remote: true do %>
    <font color="red">♥<%= book.favorites.count %></font>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book),method: :post, remote: true do %>
     ♥<%= book.favorites.count %>
  <% end %>
<% end %>

Bookers2/app/views/favorites/create.js.erb
$('#favorite_<%= @book.id%>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

Bookers2/app/views/favorites/destroy.js.erb
$('#favorite_<%= @book.id%>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

Bookers2/app/views/homes/about.html.erb
<h1 class="mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

Bookers2/app/views/homes/top.html.erb
<div class="col-11 col-sm-10 col-lg-8 col-xl-6 mx-auto">
   <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
   <p>In <i class="fas fa-book"></i>Bookers,</p>
   <p>you can share and exchange your opinions , inpressions , and emotions</p>
   <p>about various books!</p>

   <div class="btn-wrapper col-10 mx-auto">
      <%= link_to "Log in", new_user_session_path , class: 'btn btn-info btn-block' %>
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-block' %>
   </div>
</div>

Bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-1 text-white" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
              <!--サインインしている時↓　Home Users Books logout-->
              <!--Home ユーザーページ-->
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <!--Users ユーザー一覧-->
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <!--Books 投稿一覧-->
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <!--logout ログアウト-->
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i>logout
                  <% end %>
                </li>

              <% else %>
              <!--サインインしていない時↓ Home About signup login-->
                <!--Home　トップページ　homes#top(root_path)-->
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <!--About　WELCOME!!!!!!!!!!-->
                <li class="nav-item">
                  <%= link_to "/home/about", class: 'nav-link text-light' do %>
                   <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <!--sign up 新規登録-->
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i>sign up
                  <% end %>
                </li>
                <!--login ログイン-->
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i>login
                  <% end %>
                </li>
              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mt-4">
      <div class="container">
        <id class="notice"><%= flash[:notice] %></id>
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

Bookers2/app/views/users/edit.html.erb
<!--User edit-->
<div class="col-md-6 mx-auto">

  <h2>User info</h2>
  <%= form_with model: @user, local:true do |f| %>
<!--erroe messages-->
  <%= render 'books/errors', model: f.object %>
<!---->
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :profile_image, "Image" %>
    <%= f.attachment_field :profile_image %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Update User", class: 'btn btn-secondary' %>
  </div>
  <% end %>

</div>

Bookers2/app/views/users/index.html.erb
<!--users#index 一覧-->
<div class="container px-5 px-sm-0">
  <div class="row">
  <!--User info, New book-->
    <div class="col-md-3">
      <%= render partial: 'books/user', locals: {user: @user, book: @book_new} %>
    </div>

  <!--Users一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

Bookers2/app/views/users/show.html.erb
<!--users#show マイページ-->
<div class="container px-5 px-sm-0">
  <div class="row">
  <!--User info, New book-->
    <div class="col-md-3">
      <%= render partial: 'books/user', locals: {user: @user, book: @book_new} %>
    </div>

  <!--自分の投稿一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td>
              <!--いいねボタンを非同期通信で行う-->
              <div id="favorite_<%= book.id %>">
                <%= render partial: 'favorites/favorite', locals: {book: book} %>
              </div>
              <!--ここまで-->
            </td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>